export interface Campus {
    _id: string; // From MongoDB
    id?: number; // Optional original ID
    name: string;
    institutionName: string;
    municipality: string;
}

export const campusData = [
    { id: 1, name: 'SEDE TORCOROMA', institutionName: 'INST EDUCATIVA LA GARITA', municipality: 'Los Patios' },
    { id: 2, name: 'SEDE TASCARENA', institutionName: 'INST EDUCATIVA LA GARITA', municipality: 'Los Patios' },
    { id: 3, name: 'SEDE ASTILLEROS', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 4, name: 'SEDE GUADUALES', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 5, name: 'SEDE PUEBLITOS', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 6, name: 'SEDE LA UNION', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 7, name: 'SEDE CERRO LEON', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 8, name: 'SEDE RISARALDA', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 9, name: 'SEDE RANCHO GRANDE', institutionName: 'INST AGRICOLA RISARALDA', municipality: 'El Zulia' },
    { id: 10, name: 'SEDE PUERTO ESTRELLA', institutionName: 'INSTITUCION EDUCATIVA RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 11, name: 'SEDE PEDREGALES', institutionName: 'INSTITUCION EDUCATIVA RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 12, name: 'SEDE EL LLANITO', institutionName: 'INSTITUCION EDUCATIVA RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 13, name: 'SEDE FE Y ALEGRIA', institutionName: 'INSTITUCION EDUCATIVA RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 14, name: 'SEDE LA ESTANCIA', institutionName: 'INSTITUCION EDUCATIVA RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 15, name: 'SEDE PEÑALISA', institutionName: 'INSTITUCION EDUCATIVA RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 16, name: 'VEGA DE MARTINEZ', institutionName: 'INSTITUCION EDUCATIVA RURAL LA ANGELITA', municipality: 'El Zulia' },
    { id: 17, name: 'SAN MIGUEL', institutionName: 'INSTITUCION EDUCATIVA RURAL LA ANGELITA', municipality: 'El Zulia' },
    { id: 18, name: 'SAN CARLOS', institutionName: 'INSTITUCION EDUCATIVA RURAL LA ANGELITA', municipality: 'El Zulia' },
    { id: 19, name: 'LA MACARENA', institutionName: 'INSTITUCION EDUCATIVA RURAL LA ANGELITA', municipality: 'El Zulia' },
    { id: 20, name: 'SEDE VENTE DE JULIO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', municipality: 'El Zulia' },
    { id: 21, name: 'SEDE LA RAMPACHALA', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', municipality: 'El Zulia' },
    { id: 22, name: 'SEDE PLAYA COLORADA', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', municipality: 'El Zulia' },
    { id: 23, name: 'SEDE EL MESTIZO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', municipality: 'El Zulia' },
    { id: 24, name: 'SEDE EL PROGRESO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', municipality: 'El Zulia' },
    { id: 25, name: 'SEDE LA COLORADA', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JOSE DE CALASANZ', municipality: 'El Zulia' },
    { id: 26, name: 'SEDE LOS MANGOS', institutionName: 'CENTRO EDUCATIVO RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 27, name: 'SEDE LA CONQUISTA', institutionName: 'CENTRO EDUCATIVO RURAL FLORENTINO BLANCO', municipality: 'El Zulia' },
    { id: 28, name: 'CANUTILLO PARTE ALTA', institutionName: 'CENTRO EDUCATIVO RURAL BAJO PAVEZ', municipality: 'Abrego' },
    { id: 29, name: 'SEDE GAIRA', institutionName: 'CENTRO EDUCATIVO RURAL CASITAS', municipality: 'Abrego' },
    { id: 30, name: 'SEDE LLANO SUAREZ', institutionName: 'CENTRO EDUCATIVO RURAL CHAPINERO', municipality: 'Abrego' },
    { id: 31, name: 'SEDE POTRERO NUEVO', institutionName: 'CENTRO EDUCATIVO RURAL LA SIERRA', municipality: 'Abrego' },
    { id: 32, name: 'SEDE LA TEJA', institutionName: 'CENTRO EDUCATIVO RURAL LLANO ALTO', municipality: 'Abrego' },
    { id: 33, name: 'SEDE EL TARRA - SEDE PRINCIPAL', institutionName: 'INSTITUCION EDUCATIVA RURAL EL TARRA', municipality: 'Abrego' },
    { id: 34, name: 'SEDE EL LLANON', institutionName: 'INSTITUCION EDUCATIVA RURAL LA VEGA DEL TIGRE', municipality: 'Abrego' },
    { id: 35, name: 'SEDE HARAGANAZO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN JAVIER', municipality: 'Abrego' },
    { id: 36, name: 'SEDE BATROCTORA', institutionName: 'CENTRO ETNOEDUCATIVO RURAL YERARO MIMAY SASHIYI', municipality: 'Convención' },
    { id: 37, name: 'SEDE AGUA BLANCA', institutionName: 'INSTITUCION EDUCATIVA PEDRO CARREÑO LEMUS', municipality: 'Convención' },
    { id: 38, name: 'SEDE MESA RICA', institutionName: 'INSTITUCION EDUCATIVA PEDRO CARREÑO LEMUS', municipality: 'Convención' },
    { id: 39, name: 'SEDE BELLA UNION', institutionName: 'INSTITUCION EDUCATIVA RURAL EL GUAMAL', municipality: 'Convención' },
    { id: 40, name: 'SEDE SAN JUAN DE LLANOS', institutionName: 'INSTITUCION EDUCATIVA RURAL HONDURAS MOTILONIA', municipality: 'Convención' },
    { id: 41, name: 'SEDE SAN FRANCISCO', institutionName: 'INSTITUCION EDUCATIVA RURAL LUIS EDUARDO PEREZ', municipality: 'Convención' },
    { id: 42, name: 'SEDE MAICITOS', institutionName: 'INSTITUCION EDUCATIVA RURAL LUIS EDUARDO PEREZ', municipality: 'Convención' },
    { id: 43, name: 'SEDE NUEVAS HONDURAS', institutionName: 'CENTRO EDUCATIVO RURAL LLANO GRANDE', municipality: 'Convención' },
    { id: 44, name: 'SEDE SANTA RITA', institutionName: 'CENTRO EDUCATIVO RURAL EL CHAMIZON', municipality: 'El Carmen' },
    { id: 45, name: 'SEDE SAN FRANCISCO', institutionName: 'CENTRO EDUCATIVO RURAL EL SUL', municipality: 'El Carmen' },
    { id: 46, name: 'SEDE LA QUIEBRA', institutionName: 'CENTRO EDUCATIVO RURAL EL SUL', municipality: 'El Carmen' },
    { id: 47, name: 'SEDE LA PEREGRINA', institutionName: 'CENTRO EDUCATIVO RURAL EL SUL', municipality: 'El Carmen' },
    { id: 48, name: 'SEDE POTRERO GRANDE', institutionName: 'CENTRO EDUCATIVO RURAL EL SUL', municipality: 'El Carmen' },
    { id: 49, name: 'SEDE LIMONAL', institutionName: 'CENTRO EDUCATIVO RURAL EL SUL', municipality: 'El Carmen' },
    { id: 50, name: 'SEDE EL PARAISO', institutionName: 'INSTITUCION EDUCATIVA RURAL SANTA INÉS', municipality: 'El Carmen' },
    { id: 51, name: 'SEDE EL DIVISO', institutionName: 'INSTITUCION EDUCATIVA FILO EL GRINGO', municipality: 'El Tarra' },
    { id: 52, name: 'SEDE EL EDEN', institutionName: 'INSTITUCION EDUCATiva FILO EL GRINGO', municipality: 'El Tarra' },
    { id: 53, name: 'SEDE MARTILLO BAJO', institutionName: 'INSTITUCION EDUCATIVA ORU BAJO', municipality: 'El Tarra' },
    { id: 54, name: 'SEDE EL RECEPTOR', institutionName: 'INSTITUCION EDUCATIVA RURAL BELLAVISTA', municipality: 'El Tarra' },
    { id: 55, name: 'SEDE TARRA SUR', institutionName: 'INSTITUCION EDUCATIVA RURAL BRACITOS', municipality: 'El Tarra' },
    { id: 56, name: 'SEDE EL SALADO BAJO', institutionName: 'INSTITUCION EDUCATIVA RURAL DOMINGO SAVIO', municipality: 'El Tarra' },
    { id: 57, name: 'SEDE LA TORCOROMA', institutionName: 'INSTITUCION EDUCATIVA RURAL DOMINGO SAVIO', municipality: 'El Tarra' },
    { id: 58, name: 'SEDE PALO CRUZAL', institutionName: 'INSTITUCION EDUCATIVA RURAL MESITAS', municipality: 'Hacarí' },
    { id: 59, name: 'SEDE SANDOVAL', institutionName: 'INSTITUCION EDUCATIVA RURAL MESITAS', municipality: 'Hacarí' },
    { id: 60, name: 'SEDE SAN MIGUELITO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN SEBASTIAN', municipality: 'Hacarí' },
    { id: 61, name: 'SEDE DAVID HADAD SALCEDO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN SEBASTIAN', municipality: 'Hacarí' },
    { id: 62, name: 'SEDE LAS MERCEDES', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN SEBASTIAN', municipality: 'Hacarí' },
    { id: 63, name: 'SEDE EL LLANO', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN SEBASTIAN', municipality: 'Hacarí' },
    { id: 64, name: 'SEDE MANUEL DOLORES ORTIZ', institutionName: 'INSTITUCION EDUCATIVA RURAL SAN SEBASTIAN', municipality: 'Hacarí' },
    { id: 65, name: 'CENT EDUC RUR CERRO VIEJO', institutionName: 'CENTRO EDUCATIVO RURAL CERRO VIEJO', municipality: 'La Playa' },
    { id: 66, name: 'SEDE LUCIO PABON NUÑEZ', institutionName: 'INSTITUCION EDUCATIVA RURAL BENJAMIN QUINTERO ALVAREZ', municipality: 'La Playa' },
    { id: 67, name: 'SEDE EL GUAYABON', institutionName: 'INSTITUCION EDUCATIVA RURAL BENJAMIN QUINTERO ALVAREZ', municipality: 'La Playa' },
    { id: 68, name: 'SEDE CUMANA', institutionName: 'INSTITUCION EDUCATIVA RURAL BENJAMIN QUINTERO ALVAREZ', municipality: 'La Playa' },
    { id: 69, name: 'SEDE BETICAS', institutionName: 'CENTRO EDUCATIVO RURAL LLANO DE LOS ALCALDES', municipality: 'Ocaña' },
    { id: 70, name: 'SEDE EL SILENCIO', institutionName: 'INSTITUCION EDUCATIVA RURAL BALSAMINA', municipality: 'San Calixto' },
    { id: 71, name: 'SEDE SAN JERONIMO', institutionName: 'INSTITUCION EDUCATIVA RURAL BALSAMINA', municipality: 'San Calixto' },
    { id: 72, name: 'SEDE VEGA DEL PALACIO', institutionName: 'INSTITUCION EDUCATIVA RURAL BALSAMINA', municipality: 'San Calixto' },
    { id: 73, name: 'SEDE EL LORO', institutionName: 'INSTITUCION EDUCATIVA RURAL BALSAMINA', municipality: 'San Calixto' },
    { id: 74, name: 'SEDE MEDIAGUITA', institutionName: 'INSTITUCION EDUCATIVA RURAL SANTA CATALINA', municipality: 'San Calixto' },
    { id: 75, name: 'SEDE AGUA DE LA VIRGEN', institutionName: 'INSTITUCION EDUCATIVA RURAL SANTA CATALINA', municipality: 'San Calixto' },
    { id: 76, name: 'SEDE LA COLINA', institutionName: 'INSTITUCION EDUCATIVA RURAL SANTA CATALINA', municipality: 'San Calixto' },
    { id: 77, name: 'SEDE FILO REAL', institutionName: 'CENTRO EDUCATIVO RURAL SAN GIL', municipality: 'Sardinata' },
    { id: 78, name: 'SEDE PARAMILLO', institutionName: 'CENTRO EDUCATIVO RURAL SAN GIL', municipality: 'Sardinata' },
    { id: 79, name: 'SEDE CRISTALINA MACONDO', institutionName: 'INSTITUCION EDUCATIVA RURAL LA DIVINA ESPERANZA', municipality: 'Sardinata' },
    { id: 80, name: 'SEDE PORVENIR', institutionName: 'INSTITUCION EDUCATIVA RURAL NUESTRA SEÑORA DEL CARMEN', municipality: 'Sardinata' },
    { id: 81, name: 'SEDE EL GUAYABO', institutionName: 'INSTITUCION EDUCATIVA RURAL NUESTRA SEÑORA DEL CARMEN', municipality: 'Sardinata' },
    { id: 82, name: 'SEDE EL PARAMO', institutionName: 'INSTITUCION EDUCATIVA RURAL NUESTRA SEÑORA DEL CARMEN', municipality: 'Sardinata' },
    { id: 83, name: 'SEDE SANTA ANA', institutionName: 'INSTITUCION EDUCATIVA SAN LUIS BELTRAN', municipality: 'Sardinata' },
    { id: 84, name: 'SEDE LA ESTRELLA PARTE BAJA', institutionName: 'CENTRO EDUCATIVO RURAL EL FARACHE', municipality: 'Teorama' },
    { id: 85, name: 'SEDE EL LIIMON', institutionName: 'CENTRO EDUCATIVO RURAL EL FARACHE', municipality: 'Teorama' },
    { id: 86, name: 'SEDE PULPITOS', institutionName: 'CENTRO EDUCATIVO RURAL EL FARACHE', municipality: 'Teorama' },
    { id: 87, name: 'SEDE ALTA GRACIA', institutionName: 'CENTRO EDUCATIVO RURAL EL FARACHE', municipality: 'Teorama' },
    { id: 88, name: 'SEDE SAN LUIS ALTO', institutionName: 'INSTITUCION EDUCATIVA EL ASERRIO', municipality: 'Teorama' },
    { id: 89, name: 'SEDE EL ROSARIO', institutionName: 'INSTITUCION EDUCATIVA RURAL LA CECILIA', municipality: 'Teorama' },
    { id: 90, name: 'SEDE SAN JUAN DE DIOS', institutionName: 'INSTITUCION EDUCATIVA RURAL LOS MESONES', municipality: 'Teorama' },
    { id: 91, name: 'SEDE CAÑO TOMAS', institutionName: 'CENTRO EDUCATIVO RURAL LA LIBERTAD', municipality: 'Tibú' },
    { id: 92, name: 'SEDE VILLA DEL CARMEN', institutionName: 'CENTRO EDUCATIVO RURAL LA LIBERTAD', municipality: 'Tibú' },
    { id: 93, name: 'SEDE LA MEDROSA', institutionName: 'INSTITUCION EDUCATIVA HORACIO OLAVE', municipality: 'Tibú' },
    { id: 94, name: 'SEDE MIRAMONTE', institutionName: 'INSTITUCION EDUCATIVA HORACIO OLAVE', municipality: 'Tibú' },
    { id: 95, name: 'SEDE EL MILAGRO', institutionName: 'INSTITUCION EDUCATIVA RURAL KILOMETRO 15', municipality: 'Tibú' },
    { id: 96, name: 'PUERTO PALMAS', institutionName: 'INSTITUCION EDUCATIVA RURAL LA ANGALIA', municipality: 'Tibú' },
    { id: 97, name: 'SEMILLEROS DE PAZ', institutionName: 'INSTITUCION EDUCATIVA RURAL LA SERPENTINA', municipality: 'Tibú' },
    { id: 98, name: 'SEDE VETAS DE ORIENTE', institutionName: 'INSTITUCION EDUCATIVA RURAL LA SERPENTINA', municipality: 'Tibú' },
    { id: 99, name: 'ORÚ 7', institutionName: 'INSTITUCION EDUCATIVA RURAL LA SERPENTINA', municipality: 'Tibú' },
    { id: 100, name: 'SEDE SAN MARTIN', institutionName: 'INSTITUCION EDUCATIVA RURAL LA SERPENTINA', municipality: 'Tibú' },
    { id: 101, name: 'EL MILAGRO', institutionName: 'INSTITUCION EDUCATIVA RURAL LA SERPENTINA', municipality: 'Tibú' },
    { id: 102, name: 'SEDE LAS TIMBAS', institutionName: 'INSTITUCION EDUCATIVA RURAL PUERTO BARCO', municipality: 'Tibú' },
    { id: 103, name: 'SEDE LIMITES DE VILLA NUEVA', institutionName: 'INSTITUCION EDUCATIVA RURAL PUERTO BARCO', municipality: 'Tibú' },
    { id: 104, name: 'SEDE LA COLOMBIANA', institutionName: 'INSTITUCION EDUCATIVA RURAL PUERTO BARCO', municipality: 'Tibú' },
    { id: 105, name: 'SEDE ORU L5', institutionName: 'INSTITUCION EDUCATIVA RURAL BERTRANIA', municipality: 'Tibú' },
    { id: 106, name: 'SEDE LLANO DE LOS TRIGOS', institutionName: 'INSTITUCIÓN EDUCATIVA AGUAS CLARAS', municipality: 'Ocaña' },
    { id: 107, name: 'SEDE LOS CUROS PARTE ALTA', institutionName: 'CENTRO EDUCATIVO RURAL PUEBLO NUEVO', municipality: 'Ocaña' },
    { id: 108, name: 'SEDE LOS CUROS PARTE BAJA', institutionName: 'CENTRO EDUCATIVO RURAL PUEBLO NUEVO', municipality: 'Ocaña' },
    { id: 109, name: 'SEDE SUCRE', institutionName: 'INST EDUCATIVA COL FRAY JOSE MARIA AREVALO', municipality: 'La Playa' },
    { id: 110, name: 'SEDE LA LEGIA', institutionName: 'INSTITUCION EDUCATIVA RURAL BENJAMIN QUINTERO ALVAREZ', municipality: 'La Playa' },
];